const FRONT_COLOR = 'hsl(120deg, 95%, 95%)';
const BACKGROUND_COLOR = 'hsl(260deg, 5%, 5%)';
const BUTTON_TEXT_COLOR = 'hsl(260deg, 5%, 5%)';
const BUTTON_BACKGROUND_COLOR = 'hsl(120deg, 95%, 95%)';

export {FRONT_COLOR, BACKGROUND_COLOR, BUTTON_TEXT_COLOR, BUTTON_BACKGROUND_COLOR};