const FRONT_COLOR = 'hsl(120deg, 95%, 90%)';
const BACKGROUND_COLOR = 'hsl(300deg, 5%, 10%)';
const BUTTON_TEXT_COLOR = 'hsl(300deg, 5%, 10%)';
const BUTTON_BACKGROUND_COLOR = 'hsl(120deg, 95%, 90%)';

export {FRONT_COLOR, BACKGROUND_COLOR, BUTTON_TEXT_COLOR, BUTTON_BACKGROUND_COLOR};